# Generated by Django 5.2.13 on 2026-05-04 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('focus', 'Focus Block'), ('break', 'Break'), ('gym', 'Gym'), ('personal', 'Personal'), ('errand', 'Errand'), ('study', 'Study'), ('other', 'Other')], default='other', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_fixed', models.BooleanField(default=False, help_text='Cannot be moved by the planner')),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='manual', help_text='manual, google_calendar, agent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('day', 'Day Plan'), ('week', 'Week Plan'), ('replan', 'Replan')], default='day', max_length=20)),
                ('user_prompt', models.TextField(help_text='Original user request')),
                ('result_json', models.JSONField(blank=True, help_text='Generated schedule as JSON', null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Agent execution time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planning_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('optional', 'Optional')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', help_text='e.g. daily, weekly, MWF', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
