# Generated by Django 5.2.13 on 2026-05-04 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text="e.g. 'Preparing for AI exam next week'")),
                ('category', models.CharField(choices=[('goal', 'Goal'), ('constraint', 'Constraint'), ('preference', 'Preference'), ('context', 'Context'), ('habit', 'Habit')], default='context', max_length=20)),
                ('relevance_score', models.FloatField(default=1.0, help_text='0.0-1.0, decays over time')),
                ('expires_at', models.DateField(blank=True, help_text='Note becomes irrelevant after this date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='agent', help_text='agent, user, system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_notes',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_time', models.TimeField(default='07:00', help_text='Usual wake-up time')),
                ('sleep_time', models.TimeField(default='23:00', help_text='Usual bedtime')),
                ('preferred_focus_start', models.TimeField(default='09:00', help_text='Start of best focus window')),
                ('preferred_focus_end', models.TimeField(default='12:00', help_text='End of best focus window')),
                ('preferred_gym_days', models.CharField(blank=True, default='mon,wed,fri', help_text='Comma-separated: mon,tue,wed,thu,fri,sat,sun', max_length=50)),
                ('preferred_gym_time', models.TimeField(blank=True, default='17:00', null=True)),
                ('gym_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_meetings_per_day', models.PositiveIntegerField(default=4)),
                ('preferred_break_duration', models.PositiveIntegerField(default=15, help_text='Break duration in minutes')),
                ('lunch_start', models.TimeField(default='12:30')),
                ('lunch_duration_minutes', models.PositiveIntegerField(default=60)),
                ('preferred_task_block_minutes', models.PositiveIntegerField(default=90, help_text='Ideal task block length')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='BehavioralMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(help_text='e.g. task_completion_rate, avg_postponements, focus_adherence', max_length=100)),
                ('metric_value', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'behavioral_metrics',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'metric_name', 'period_start')},
            },
        ),
    ]
